name: FireFly
version: ${project.version}
main: firefly.firefly.FireFly
api-version: 1.16
authors: [ MicrosoftWord12 ]
description: Custom Mod

# Command Section
commands:
  DBinit:
    permission: FireFly.DB.Admin
    usage: /DBinit
    aliases:
      - dbInit
      - DBINIT
      - databaseInit

  claim:
    permission: FireFly.ClaimChunk
    permission-message: You don't have the claim chunk permission
    description: Claims a chunk for a specified player
    usage: /claim
    aliases:
      - claim
      - Claim
      - ChunkClaim
      - chunk

  removeClaim:
    permission: FireFly.ClaimChunk
    permission-message: You don't have the claim chunk permission
    description: Removes a player from chunk
    usage: /RemovePlayerFromChunk
    aliases:
      - removePlayer
      - playerRemove

  addPlayerToClaim:
    permission: FireFly.ClaimChunk
    permission-message: You don't have the claim chunk permission
    description: Adds a player to the chunk
    usage: /addPlayerToClaim <PLAYER TO ADD>
    aliases:
      - addPlayer
      - playerAdd
  removePlayerFromClaim:
    permission: FireFly.ClaimChunk
    permission-message: You don't have the claim chunk permision
    description: Removes a player from the owner's chunk
    usage: /removePlayerFromClaim <PLAYER TO REMOVE>

  Kick:
    permission: FireFly.KickMember
    permission-message: You do not have the permission (FireFly.KickMember)
    description: Kick a specified player from the server
    usage: /kick <PLAYER> <REASON>
    aliases:
      - kick
      - kick
      - kck

  Feed:
    description: Feed yourself
#    usage: /Feed
    aliases:
      - fed
      - feed

  Heal:
    description: Heal yourself
#    usage: /Heal
    aliases:
      - heal

  Invisible:
    permission: FireFly.Invisible
    permission-message: You do not have the permission (FireFly.Invisible)
    description: Go invisible
#    usage: /invisible
    aliases:
      - hide
      - hid
      - vanish

  Invulnerable:
    permission: FireFly.Invulnerable
    permission-message: You do not have the permission (FireFly.Invulnerable)
    description: Go Invulnerable
#    usage: /invulnerable
    aliases:
      - god
      - invulnerable
      - God

  freeze:
    permission: FireFly.Freeze
    permission-message: You do not hav ethe permission (FireFly.Freeze)
    description: Able to Freeze people
    usage: /freeze <PLAYER>
    aliases:
      - Freeze

# Permissions section
permissions:
  FireFly.*:
    description: Gets All FireFly Permissions
    default: op
    children:
#      - FireFly.KickMember
      - FireFly.PlayerMove
      - FireFly.seeAvailableCommands
      - FireFly.Give
      - FireFly.Invisible
      - FireFly.Invulnerable
      - FireFly.SwitchGamemode
      - FireFly.ClaimChunk

  FireFly.KickMember:
    description: Permission to allows someone to kick a player
    default: op

  FireFly.PlayerMove:
    description: Permission to allow a player to move
    default: op

  FireFly.seeAvailableCommands:
    description: Permission to allow people to see the server's commands
    default: op

  FireFly.Give:
    description: Permission to be able to give a player an item(S)
    default: op

  FireFly.Invisible:
    description: Permission to go invisible
    default: op

  FireFly.Invulnerable:
    description: Permission for going into God Mode
    default: op

  FireFly.SwitchGamemode:
    description: Permission for switching a player gamemode
    default: op

  FireFly.DB.Admin:
    description: Database Administration
    default: false

  FireFly.ClaimChunk:
    description: Claims Chunk
    default: true

  FireFly.Freeze:
    description: Able to freeze people
    default: op

